-- Migration: 20261008000001_pg_cron_analytics.sql
-- Description: Sets up a pg_cron durable background job for analytics aggregation.

BEGIN;

-- 1. Create the aggregated table for daily summaries
CREATE TABLE IF NOT EXISTS public.daily_user_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  summary_date DATE NOT NULL,
  total_events INT DEFAULT 0,
  crashes_reported INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, summary_date)
);

-- Enable RLS on summaries
ALTER TABLE public.daily_user_summaries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can view summaries" ON public.daily_user_summaries FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 2. Create the Idempotent Worker Function
CREATE OR REPLACE FUNCTION public.aggregate_daily_analytics()
RETURNS void AS $$
DECLARE
  target_date DATE := CURRENT_DATE - INTERVAL '1 day';
BEGIN
  -- Idempotent UPSERT: Aggregates events from yesterday. 
  -- If it runs twice, it simply overwrites the existing row with the exact same aggregated data.
  INSERT INTO public.daily_user_summaries (user_id, summary_date, total_events, crashes_reported)
  SELECT 
    user_id,
    target_date,
    COUNT(*),
    COUNT(*) FILTER (WHERE event_type = 'emergency_dispatched')
  FROM public.activity_events
  WHERE DATE(created_at) = target_date AND user_id IS NOT NULL
  GROUP BY user_id
  ON CONFLICT (user_id, summary_date) 
  DO UPDATE SET 
    total_events = EXCLUDED.total_events,
    crashes_reported = EXCLUDED.crashes_reported;

  -- Cleanup abandoned/raw telemetry older than 7 days to preserve disk space
  DELETE FROM public.activity_events 
  WHERE created_at < NOW() - INTERVAL '7 days';
  
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Schedule the pg_cron Job
-- Note: pg_cron requires the pg_cron extension to be enabled in Supabase via:
-- CREATE EXTENSION IF NOT EXISTS pg_cron;
-- We do not automatically enable it here as it requires postgres superuser privileges.
-- 
-- To schedule the job to run daily at 2:00 AM UTC:
-- SELECT cron.schedule('aggregate_analytics', '0 2 * * *', 'SELECT public.aggregate_daily_analytics();');

COMMIT;
